[package]
name = "statevec-macros"
version = "0.2.1"
edition = "2024"
rust-version = "1.91"
description = "Procedural macros for schema-first StateVec domain definitions."
license.workspace = true
repository.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
statevec_model.workspace = true
proc-macro2.workspace = true
quote.workspace = true
smallvec.workspace = true
syn.workspace = true

[dev-dependencies]
statevec_api.workspace = true
test-case = "3.3.1"
trybuild.workspace = true

[lib]
proc-macro = true
